global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'airflow'
    static_configs:
      - targets: ['lakehouse-metrics-exporter:8000']

  - job_name: 'containers'
    static_configs:
      - targets: ['lakehouse-cadvisor:8080']

  - job_name: 'spark'
    static_configs:
      - targets: ['lakehouse-spark-master:8080']
