# File: dbt_project/dbt_project.yml
name: 'hanoi_tourism_lakehouse'
version: '1.0.0'
config-version: 2
 
profile: 'lakehouse'
model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
 
models:
  hanoi_tourism_lakehouse:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
